name: Generate Artifacts

on:
  workflow_dispatch:
    inputs:
      month:
        description: "Enter the month to filter in '2024-06' format"
        required: true
        default: "2023-03"

  push:
    branches:
      - main

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas matplotlib openpyxl

      - name: Run artifact generation script
        run: python filter_and_visualize.py ${{ github.event.inputs.month }}

      - name: Upload pie chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: piechart
          path: artifacts/piechart.png

      - name: Upload bar chart artifact
        uses: actions/upload-artifact@v3
        with:
          name: barchart
          path: artifacts/barchart.png
