name: Monthly Finance Report

on:
  workflow_dispatch:      # Enables manual triggering
    inputs:
      month:
        description: "Month to generate report for (1-12)"
        required: true
        default: "10"

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib openpyxl

    - name: Generate Monthly Report
      run: python src/filter_and_visualize.py ${{ github.event.inputs.month }}

    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: monthly_report
        path: output/monthly_report.png
