name: Monthly Finance Report

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st day of every month at midnight
  workflow_dispatch:      # Allows manual triggering

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib openpyxl

    - name: Generate Monthly Report
      run: python src/filter_and_visualize.py

    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: monthly_report
        path: output/monthly_report.png
